/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @fk-jupyterlab/buildutils */
import '@lumino/widgets/style/index.js';
import '@fk-jupyterlab/ui-components/style/index.js';
import '@fk-jupyterlab/apputils/style/index.js';
import '@lumino/dragdrop/style/index.js';
import '@fk-jupyterlab/codeeditor/style/index.js';
import '@fk-jupyterlab/codemirror/style/index.js';
import '@fk-jupyterlab/rendermime/style/index.js';
import '@fk-jupyterlab/attachments/style/index.js';
import '@fk-jupyterlab/filebrowser/style/index.js';
import '@fk-jupyterlab/outputarea/style/index.js';

import './base.css';
