/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @fk-jupyterlab/buildutils */
import '@lumino/widgets/style/index.js';
import '@fk-jupyterlab/ui-components/style/index.js';
import '@fk-jupyterlab/apputils/style/index.js';
import '@fk-jupyterlab/rendermime/style/index.js';
import '@fk-jupyterlab/docregistry/style/index.js';
import '@fk-jupyterlab/docmanager/style/index.js';
import '@fk-jupyterlab/cells/style/index.js';
import '@fk-jupyterlab/fileeditor/style/index.js';
import '@fk-jupyterlab/markdownviewer/style/index.js';
import '@fk-jupyterlab/notebook/style/index.js';

import './base.css';
