/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @fk-jupyterlab/buildutils */
import '@fk-jupyterlab/apputils/style/index.js';
import '@fk-jupyterlab/codeeditor/style/index.js';
import '@fk-jupyterlab/docregistry/style/index.js';
import '@fk-jupyterlab/application/style/index.js';
import '@fk-jupyterlab/console/style/index.js';
import '@fk-jupyterlab/fileeditor/style/index.js';
import '@fk-jupyterlab/notebook/style/index.js';
import '@fk-jupyterlab/debugger/style/index.js';
