/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

/* This file was auto-generated by ensurePackage() in @fk-jupyterlab/buildutils */
import '@lumino/widgets/style/index.js';
import '@fk-jupyterlab/ui-components/style/index.js';
import '@fk-jupyterlab/apputils/style/index.js';
import '@fk-jupyterlab/application/style/index.js';
import '@fk-jupyterlab/launcher/style/index.js';
import '@fk-jupyterlab/mainmenu/style/index.js';
import '@fk-jupyterlab/running/style/index.js';
import '@fk-jupyterlab/terminal/style/index.js';
